<?php
/**
 * @version    3.6.0
 * @package    Com_Ra_tools
 * @author     Charlie Bigley <charlie@bigley.me.uk>
 * @copyright  2025 Charlie Bigley
 * @license    GNU General Public License version 2 or later; see LICENSE.txt
 * 24/01/26 Generated by component-generator.com
 15/04/26 CB updateClusters (from Area_lstController)
 */

namespace Ramblers\Component\Ra_tools\Administrator\Controller;

\defined('_JEXEC') or die;

use Joomla\CMS\Application\SiteApplication;
use Joomla\CMS\Factory;
use Joomla\CMS\Language\Multilanguage;
use Joomla\CMS\Language\Text;
use Joomla\CMS\MVC\Controller\AdminController;
use Joomla\CMS\Router\Route;
use Joomla\CMS\Uri\Uri;
use Joomla\Utilities\ArrayHelper;
use Ramblers\Component\Ra_tools\Site\Helpers\ToolsHelper;

/**
 * Clusters list controller class.
 *
 * @since  3.4.8
 */
class ClustersController extends AdminController
{

	/**
	 * Method to clone existing Clusters
	 *
	 * @return  void
	 *
	 * @throws  Exception
	 */
	public function duplicate()
	{
		// Check for request forgeries
		$this->checkToken();

		// Get id(s)
		$pks = $this->input->post->get('cid', array(), 'array');

		try
		{
			if (empty($pks))
			{
				throw new \Exception(Text::_('COM_RA_TOOLS_NO_ELEMENT_SELECTED'));
			}

			ArrayHelper::toInteger($pks);
			$model = $this->getModel();
			$model->duplicate($pks);
			$this->setMessage(Text::_('COM_RA_TOOLS_ITEMS_SUCCESS_DUPLICATED'));
		}
		catch (\Exception $e)
		{
			Factory::getApplication()->enqueueMessage($e->getMessage(), 'warning');
		}

		$this->setRedirect('index.php?option=com_ra_tools&view=clusters');
	}

	/**
	 * Proxy for getModel.
	 *
	 * @param   string  $name    Optional. Model name
	 * @param   string  $prefix  Optional. Class prefix
	 * @param   array   $config  Optional. Configuration array for model
	 *
	 * @return  object	The Model
	 *
	 * @since   3.4.8
	 */
	public function getModel($name = 'Cluster', $prefix = 'Administrator', $config = array())
	{
		return parent::getModel($name, $prefix, array('ignore_request' => true));
	}

	

	/**
	 * Method to save the submitted ordering values for records via AJAX.
	 *
	 * @return  void
	 *
	 * @since   3.4.8
	 *
	 * @throws  Exception
	 */
	public function saveOrderAjax()
	{
		// Get the input
		$pks   = $this->input->post->get('cid', array(), 'array');
		$order = $this->input->post->get('order', array(), 'array');

		// Sanitize the input
		ArrayHelper::toInteger($pks);
		ArrayHelper::toInteger($order);

		// Get the model
		$model = $this->getModel();

		// Save the ordering
		$return = $model->saveorder($pks, $order);

		if ($return)
		{
			echo "1";
		}

		// Close the application
		Factory::getApplication()->close();
	}

    public function updateClusters() { // localhost/administrator/index.php?option=com_ra_tools&task=clusters.updateClusters
        $toolsHelper = new ToolsHelper;
        $sql = 'SELECT * FROM #__ra_clusters';
        $clusters = $toolsHelper->getRows($sql);

        foreach ($clusters as $cluster) {
//            $update_sql = 'UPDATE `#__ra_organisations` SET cluster = "' . $cluster->code . '" ';
            $update_sql = 'UPDATE `#__ra_areas` SET cluster = "' . $cluster->code . '" ';
            $update_sql .= 'WHERE code in (';
            $update_sql .= '"' . str_replace(',', '","', $cluster->area_list) . '")';
            echo "$update_sql<br>";
            $toolsHelper->executeCmd($update_sql);
        }

        $sql = 'SELECT code FROM #__ra_areas WHERE cluster IS NULL ORDER BY code';
        $rows = $toolsHelper->getRows($sql);
        if (count($rows) > 0) {
            echo "Areas without cluster code<br>";
            foreach ($rows as $row) {
                echo $row->code . ',';
            }
        }    
        $back = '/administrator/index.php?option=com_ra_tools&view=clusters';
        echo $toolsHelper->backButton($back);
    }
}
