<?php
/**
 * @version    3.5.3
 * @package    com_ra_tools
 * @author     Charlie Bigley <charlie@bigley.me.uk>
 * @copyright  2025 Charlie Bigley
 * @license    GNU General Public License version 2 or later; see LICENSE.txt
 * 24/01/26 Generated by component-generator.com
 * 26/01/26 CB add contact_id
 */

// No direct access
defined('_JEXEC') or die;

use \Joomla\CMS\HTML\HTMLHelper;
use \Joomla\CMS\Factory;
use \Joomla\CMS\Uri\Uri;
use \Joomla\CMS\Router\Route;
use \Joomla\CMS\Language\Text;

$wa = $this->document->getWebAssetManager();
$wa->useScript('keepalive')
	->useScript('form.validate');
HTMLHelper::_('bootstrap.tooltip');
?>

<form
	action="<?php echo Route::_('index.php?option=com_ra_tools&layout=edit&id=' . (int) $this->item->id); ?>"
	method="post" enctype="multipart/form-data" name="adminForm" id="cluster-form" class="form-validate form-horizontal">

	<div class="row-fluid">
		<div class="col-md-12 form-horizontal">
			<fieldset class="adminform">		
				<?php 
				echo $this->form->renderField('code');
				echo $this->form->renderField('name'); 
				echo $this->form->renderField('area_list');
				echo $this->form->renderField('website');
				echo $this->form->renderField('contact_id');
				?>
			</fieldset>
		</div>
	</div>
	<input type="hidden" name="jform[id]" value="<?php echo isset($this->item->id) ? $this->item->id : ''; ?>" />	

	<input type="hidden" name="task" value=""/>
	<?php echo HTMLHelper::_('form.token'); ?>

</form>
